---
- hosts: all
  become: true

  roles:
    - role: robertdebock.epel
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: robertdebock.locale
